[project]
name = "memento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "openai>=2.16.0",
    "pydantic>=2.12.5",
    "pinecone>=8.0.0",
    "python-dotenv>=1.0.1",
    "sentence-transformers>=5.2.2",
]
